#!/bin/sh

set -e

MESH_STATUS_HOME="${MESH_STATUS_HOME:-$HOME/.local/meshtest}"
case "$MESH_STATUS_HOME" in
    /*) ;;  # already absolute
    *) MESH_STATUS_HOME="$PWD/$MESH_STATUS_HOME" ;;
esac
MESH_STATUS_VERSION="${MESH_STATUS_VERSION:-main}"
MESH_STATUS_LOCAL_SOURCE="${MESH_STATUS_LOCAL_SOURCE:-}"
REPO_URL="${MESH_STATUS_REPO:-https://github.com/opencode-ai/mesh-status.git}"

YES=0

usage() {
    cat <<EOF
install.sh — Install mesh-status

Usage: curl -fsSL https://raw.githubusercontent.com/opencode-ai/mesh-status/main/deploy/install.sh | sh [options]

Options:
  -y, --yes              Non-interactive mode (skip all prompts)
  --help                 Show this help message

Environment variables:
  MESH_STATUS_HOME       Install directory (default: ~/.local/meshtest)
  MESH_STATUS_VERSION    Git ref to install (default: main)
  MESH_STATUS_REPO       Repository URL (default: github.com/opencode-ai/mesh-status.git)
EOF
    exit 0
}

for arg in "$@"; do
    case "$arg" in
        -y|--yes) YES=1 ;;
        -h|--help) usage ;;
    esac
done

echo "Checking prerequisites..."

missing_prereq() {
    echo ""
    echo "Error: $1 is required but not found."
    echo ""
    case "$1" in
        uv)   echo "  Install uv: curl -LsSf https://astral.sh/uv/install.sh | sh" ;;
        git)  echo "  Install git: https://git-scm.com/downloads" ;;
        curl) echo "  Install curl using your system package manager" ;;
        npm)  echo "  Install Node.js/npm: https://nodejs.org/" ;;
    esac
    echo ""
    exit 1
}

command -v uv >/dev/null 2>&1 || missing_prereq uv
command -v git >/dev/null 2>&1 || missing_prereq git
command -v curl >/dev/null 2>&1 || missing_prereq curl
command -v npm >/dev/null 2>&1 || missing_prereq npm

if [ "$YES" = 0 ]; then
    printf "Install mesh-status to %s? [Y/n] " "$MESH_STATUS_HOME"
    read -r CONFIRM
    case "$CONFIRM" in
        n*|N*) echo "Aborted."; exit 1 ;;
    esac
fi

if [ -f "$MESH_STATUS_HOME/.mesh-status.install" ] && [ -d "$MESH_STATUS_HOME/.git" ]; then
    echo "Existing install detected at $MESH_STATUS_HOME — updating..."
    cd "$MESH_STATUS_HOME"
    git fetch --tags
    git checkout "$MESH_STATUS_VERSION"
elif [ -n "$MESH_STATUS_LOCAL_SOURCE" ]; then
    echo "Copying mesh-status from $MESH_STATUS_LOCAL_SOURCE to $MESH_STATUS_HOME..."
    mkdir -p "$(dirname "$MESH_STATUS_HOME")"
    if [ -f "$MESH_STATUS_HOME/.env" ]; then
        cp "$MESH_STATUS_HOME/.env" /tmp/_mesh_env_backup
    fi
    rm -rf "$MESH_STATUS_HOME"
    cp -a "$MESH_STATUS_LOCAL_SOURCE" "$MESH_STATUS_HOME"
    if [ -f /tmp/_mesh_env_backup ]; then
        mv /tmp/_mesh_env_backup "$MESH_STATUS_HOME/.env"
        echo "Existing .env preserved"
        rm -f /tmp/_mesh_env_backup 2>/dev/null || true
    fi
    cd "$MESH_STATUS_HOME"
else
    echo "Cloning mesh-status ($MESH_STATUS_VERSION) to $MESH_STATUS_HOME..."
    mkdir -p "$(dirname "$MESH_STATUS_HOME")"
    git clone --depth 1 --branch "$MESH_STATUS_VERSION" "$REPO_URL" "$MESH_STATUS_HOME"
    cd "$MESH_STATUS_HOME"
fi

echo "Installing Python dependencies..."
uv sync

echo "Building frontend..."
cd frontend
npm ci
npm run build
cd ..

echo "$MESH_STATUS_VERSION" > "$MESH_STATUS_HOME/.mesh-status.install"

if [ ! -f "$MESH_STATUS_HOME/.env" ]; then
    cat > "$MESH_STATUS_HOME/.env" <<EOF
# mesh-status configuration
# Generated by install.sh on $(date)
LEADER_URL=http://0.0.0.0:58080
LEADER_HOST=0.0.0.0
DATA_DIR=$MESH_STATUS_HOME/data
EOF
else
    echo "Existing .env found — preserving user configuration"
fi

echo ""
echo "────────────────────────────────────────────────"
echo " mesh-status installed to $MESH_STATUS_HOME"
echo ""
echo " Start the leader:   $MESH_STATUS_HOME/start.sh --leader"
echo " Start the node:     $MESH_STATUS_HOME/start.sh --node"
echo ""
echo " Dashboard:          http://localhost:58080"
echo ""
echo " To uninstall:       $MESH_STATUS_HOME/start.sh --uninstall"
echo "────────────────────────────────────────────────"
