import os

DEFAULT_PORT = 58080
CHECK_INTERVAL = int(os.environ.get("MESH_STATUS_INTERVAL", "10"))
PEER_PUSH_TIMEOUT = int(os.environ.get("MESH_STATUS_PEER_PUSH_TIMEOUT", "5"))
LOG_LEVEL = os.environ.get("MESH_STATUS_LOG_LEVEL", "INFO")
BUFFER_SIZE = int(os.environ.get("MESH_STATUS_BUFFER_SIZE", "20000"))
